# This workflow will build a wheel for the project

name: Build Wheel

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
        pip install .
    - name: Build the wheel
      run: |
        python -m build --wheel
    - uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/deep_audio_dataset-*-py3-none-any.whl
